config/routes.rb
Rails.application.routes.draw do
 
  get 'programas/index'
  devise_for :users
  root to: "dashboard#index"

  # delete "areas/:id" => "areas#destroy"
  # get '/areas/:id/edit', to: 'areas#edit',  as: 'edit_area'
  # put '/areas/:id', to: 'areas#update'

  # delete "areas/:area_id/programas/:id" => "areas/programas#destroy"
  # get 'areas/:area_id/programas/:id/edit', to: 'areas/programas#edit',  as: 'edit_programa'
  # put '/areas/:area_id/programas/:id', to: 'areas/programas#update'
  

  resources :areas do
    resources :programas, module: :areas
  end

  resources :programas do
    resources :cursos, module: :programas
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
    validates :nombreArea, uniqueness: true
    has_many :programas, dependent: :destroy
    mount_uploader :avatar, AvatarUploader
end

app/models/curso.rb
class Curso < ApplicationRecord
  validates :ficha, uniqueness: true
  belongs_to :programa
end

app/models/programa.rb
class Programa < ApplicationRecord
  validates :nombre, uniqueness: true
  belongs_to :area
  has_many :curso, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  after_create :welcome_send
  def welcome_send
    WelcomeMailer.welcome_send(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas/programas_controller.rb
class Areas::ProgramasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_area

  def index
    @programas = @area.programas
  end

  def show
    @programa = @area.programas.find(params[:id])
  end

  def new
    @programa = @area.programas.new
  end

  def edit
    @programa = @area.programas.find(params[:id])
  end

  def update
    @programa = @area.programas.find(params[:id])
    if @programa.update(programa_params_update)
      redirect_to area_programas_url
    else
      render :edit
    end
  end

  def destroy
    @programa = @area.programas.find(params[:id])
    if @programa.destroy
      flash[:alert] = "Programa eliminado correctamente"
    redirect_to area_programas_url
    else 
      flash[:alert] = "Error al eliminar el programa"
    end
  end

  def create
    @programa = @area.programas.new(programa_params)
    if @programa.save 
        flash[:notice] = "Programa creado correctamente"
        redirect_to area_programas_url
    else
      render :new
    end
  end

  private

  def set_area
    @area = Area.find(params[:area_id])
  end

  def programa_params
    params.require(:programa).permit(:nombre)
  end

  def programa_params_update
    params.require(:programa).permit(:nombre)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_area, only: [:show, :edit, :destroy]
  def index
    @areas = Area.all
    
  end

  def show
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save 
      flash[:notice] = "Area creada correctamente"
      redirect_to areas_path
    else
      render :new
    end
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params_update)
      redirect_to areas_path
    else
      render :edit
    end
  end

  def destroy
    @area = Area.find(params[:id])
    if @area.destroy
      flash[:alert] = "Area eliminada correctamente"
      redirect_to areas_path
    end
  end

  private

  def set_area
    @area = Area.find(params[:id])
  end

  def area_params_update
    params.require(:area).permit(:nombreArea, :avatar)
  end

  def area_params
    params.require(:area).permit(:nombreArea, :avatar)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/programas/cursos_controller.rb
class Programas::CursosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_programa
  
  def index
    @cursos = @programa.curso
  end

  def show
    @curso = @programa.curso.find(params[:id])
  end

  def new
    @curso = @programa.curso.new
  end

  def create
    @curso = @programa.curso.new(curso_params)
    if @curso.save
      flash[:notice] = "Ficha registrada correctamente"
      redirect_to programa_cursos_url
    else 
      flash[:alert] = "Error al registrar la ficha"
      render :new
    end
  end

  def edit
    @curso = @programa.curso.find(params[:id])
  end

  def update
    @curso = @programa.curso.find(params[:id])
    if @curso.update(update_curso_params)
        redirect_to programa_cursos_url
    else
      render :edit
    end
  end

  def destroy
    @curso = @programa.curso.find(params[:id])
    if @curso.destroy
      flash[:alert] = "Codigo de ficha eliminado correctamente"
    redirect_to programa_cursos_url
    else
      flash[:alert] = "Error al eliminar al eliminar el numero de ficha"
    end
  end

  private

  def set_programa
    @programa = Programa.find(params[:programa_id])
  end

  def update_curso_params
    params.require(:curso).permit(:ficha)
  end

  def curso_params
    params.require(:curso).permit(:ficha)
  end
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  before_action :authenticate_user!
  def index
    @programas = Programa.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key
      when 'notice' then 'alert-success'
      when 'alert' then 'alert-danger'
    end
  end
end

app/helpers/areas/programas_helper.rb
module Areas::ProgramasHelper
  # def flash_class(key)
  #   case key
  #     when 'notice' then 'alert-success'
  #     when 'alert' then 'alert-danger'
  #   end
  # end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/programas/cursos_helper.rb
module Programas::CursosHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/areas/_area.html.erb
<tbody>
  <tr>
    <td>
      <div  id="imagen">
        <nav id="menu">
          <ul>
            <li><i class="fa fa-bars" aria-hidden="true"></i>
              <ul>
                <li>
                  <%= button_to 'Editar' , edit_area_url(area), :method=> :get,form: {data: {turbo_confirm: 'Desea editar esta Area'} }, id:"opctionMenu"%>
                </li>
                <li>
                  <%= button_to 'Eliminar' , area, method: :delete, form: {data:
                    {turbo_confirm: 'Desea eliminar esta Area' } }, id:"opctionMenu"%>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
        <a href="<%= area_programas_url(area) %>" class="link" >
          <%= image_tag area.avatar_url if area.avatar.present? %>
        </a>
      </div>
      <%= button_to area.nombreArea, area_programas_url(area), method: :get, id:"nombreArea"%>
    </td>
  </tr>
</tbody>

app/views/areas/_form.html.erb
<%= simple_form_for @area do |f| %>
  <div class="inputNewArea">
    <div class="form-group">
      <%= f.input :avatar, as: :file, label: false, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_field :nombreArea, placeholder:"ingrese nombre del area", id:"inputNewArea", required:true%>
    </div>
    <%= f.submit "Guardar" , class:"botonNewArea", id:"botonNewArea"%>
      <% end %>
  </div>

app/views/areas/create.html.erb
<h1>Areas#create</h1>
<p>Find me in app/views/areas/create.html.erb</p>

app/views/areas/edit.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", areas_path, method: :get, class:
      "IndexArea"%>
    </div>
  </aside>
 <article>
  <legend id="titleNewArea">Editar Area</legend>
  <%= render "form" %>
 </article>
</section>
<%= render 'layouts/footer' %>

app/views/areas/index.html.erb
<%= render 'layouts/navbar' %>

  <section class="menuArea">
    <aside class="OpcionesArea">
      <div class="LinkAreas" id="LinkAreas">
        <i class="fa fa-home" aria-hidden="true" id="Icono"></i>
        <%= link_to "Inicio" , root_path, method: :get, class: "IndexArea" %>
      </div>
      <div class="LinkAreas" id="LinkAreas">
        <i class="fa fa-plus-circle" aria-hidden="true" id="Icono"></i>
        <%= link_to "Nuevo Area" , new_area_path, method: :get, class: "IndexArea" %>
      </div>
    </aside>
    <article>
      <table id="infoTable">
        <thead id="titleTable">
          <tr>
            <th colspan="2">Areas</th>
          </tr>
        </thead>
        <%= render @areas %>
        
      </table>
    </article>
  </section>
  <%= render 'layouts/footer' %>


  

app/views/areas/new.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", areas_path, method: :get, class:
      "IndexArea"%>
    </div>
  </aside>
 <article>
  <legend id="titleNewArea">Registrar Area</legend>
  <%= render "form" %>
 </article>
</section>
<%= render 'layouts/footer' %>

app/views/areas/programas/_form.html.erb
<%= simple_form_for [@area, @programa] do |f| %>

<div class="inputNewArea">
  <div class="form-group">
    <%= f.text_field :nombre, placeholder:"ingrese nombre del programa",
    id:"inputNewArea" ,required:"true"%>
  </div>
  <%= f.submit "Guardar", class:"botonNewArea", id:"botonNewArea" %> <% end %>
</div>

app/views/areas/programas/_programa.html.erb
<tbody>
  <tr>
    <td colspan="2",id="BotonArea" >
        <%= button_to programa.nombre, programa_cursos_url(programa),method: :get,id:"linkBotonArea"%>
    </td>
    <td id="botonesAccion">
      <%= button_to 'Editar', edit_area_programa_url(programa.area, programa), :method => :get, id:"BotonAccion", form: {data: {turbo_confirm: 'Desea editar este programa'} }  %>
      <%= button_to 'Eliminar', [programa.area, programa], method: :delete, id:"BotonAccion", form: {data: {turbo_confirm: 'Desea eliminar este programa'} } %>  
    </td>
  </tr>  
</tbody>

app/views/areas/programas/edit.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", areas_path, method: :get, class:
      "IndexArea"%>
    </div>
  </aside>
 <article>
  <legend id="titleNewArea">Editar Programa</legend>
  <%= render "form" %>
 </article>
</section>
<%= render 'layouts/footer' %>

app/views/areas/programas/index.html.erb
<%= render 'layouts/navbar' %>
<h2 id="titleProgramasArea">Programas Area de <%= @area.nombreArea %></h2>
<section class="menuArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", areas_path, method: :get, class: "IndexArea"%>
    </div>
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-plus-circle" aria-hidden="true" id="Icono"></i>
      <%= link_to "Nuevo Programa", new_area_programa_url, method: :get, class:
      "IndexArea"%>
    </div>
  </aside>

  <article class="Areas">
    <table class="table">
      <thead id="encabezado">
        <tr>
          <th id="nombreAreas">Programa</th>
          <th id="nombreAreas" colspan="2">Acciones</th>
        </tr>
      </thead>
      <%= render @programas %>
    </table>
  </article>
</section>
<%= render 'layouts/footer' %>

app/views/areas/programas/new.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", areas_path, method: :get, class:
      "IndexArea"%>
    </div>
  </aside>
 <article>
  <legend id="titleNewArea">Registrar Programa</legend>
  <%= render "form" %>
 </article>
</section>
<%= render 'layouts/footer' %>

app/views/areas/programas/show.html.erb
<h1>Areas::Programas#show</h1>
<p>Find me in app/views/areas/programas/show.html.erb</p>

<%= @programa.nombre %>
<%= link_to "Agregar Ficha", new_programa_curso_url, method: :get, class:
      "IndexArea"%>

app/views/areas/show.html.erb
<h1>Areas#show</h1>
<p>Find me in app/views/areas/show.html.erb</p>

app/views/areas/update.html.erb
<h1>Areas#update</h1>
<p>Find me in app/views/areas/update.html.erb</p>

app/views/dashboard/index.html.erb
<%= render 'layouts/navbar' %>
<section class="menuOpciones">
  <aside class="Opciones">
    <div class="LinkAreas" id="LinkMenu">
      <i class="fa fa-home" aria-hidden="true" id="Icono"></i>
      <%= link_to "Inicio", root_path, method: :get, class: "IndexArea"%>
    </div>
    <div class="containerLink" id="containerLink">
      <i class="fa fa-list" aria-hidden="true" id="Icono"></i>
      <%= link_to "Areas", areas_path,:method => :get,class:"linkIndex"%>
    </div>
  </aside>
  <article class="textBienvenida">
    <h1 class="titleBienvenida">Bienvenido</h1>
    <p class="messageBienvenida">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    </p>
  </article>
</section>
<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer class="application">
  <div class="containerFooter">
      <p id="textFooter">Version 1.0.1</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<body>
  <header>
    <%= link_to root_path do %>
      <%= image_tag "logo-sena.ico",:alt => "Logo", :class => "logoNav"%>
    <% end %>
  
    <nav>
      <ul class="nav__links">
        <li><%= link_to "Inicio", root_path %></li>
        <!--  <li><a href="#">Areas</a></li>
        <li><a href="#">Programas</a></li>
        <li><a href="#">Cursos</a></li> -->
        <li>
          <%= link_to "Cerrar sesion", destroy_user_session_path, method:
          :delete, class:"cta"%>
        </li>
      </ul>
    </nav>
    <p class="menu cta">Menu</p>
  </header>
  <div class="overlay">
    <a class="close">&times;</a>
    <div class="overlay__content">
      <a href="#">Areas</a>
      <a href="#">Programas</a>
      <a href="#">Cursos</a>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>https://www.AppRuby.com</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

  <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>

</head>

<body class="vistaInicio">
  <main>
    <%= yield %>
      <% flash.each do |key, value| %>
        <div class="alert <%= flash_class(key)%>" id="flash-alert" onclick="cerrar()">
          <%= value %>
            <!--  <button class="close" onclick="cerrar()">&times;</button> -->
        </div>
        <% end %>
  </main>
  <script>
    /*  function cerrar(){
      document.getElementById("flash-alert").style.display = "none"; 
    } */

    setTimeout(() => {
      document.getElementById("flash-alert").style.display = "none";
    }, 3000); 
  </script>

</body>

</html>

app/views/programas/cursos/_curso.html.erb
<tr>
  <td id="line2"><%= curso.ficha %></td>
  <td id="botonesAccion">
    <%= button_to 'Editar', edit_programa_curso_url(@programa,curso),
    :method => :get, id:"BotonAccion",form: {data: {turbo_confirm: 'Desea editar este ficha'} } %>
    
    <%= button_to 'Eliminar', programa_curso_url(@programa,curso),
    :method => :delete, id:"BotonAccion", form: {data: {turbo_confirm: 'Desea eliminar esta ficha'} } %>
  </td>
</tr>

app/views/programas/cursos/_form.html.erb
<%= simple_form_for [@programa, @curso] do |f| %>

<div class="inputNewArea">
  <div class="form-group">
  <%= f.text_field :ficha, placeholder:"ingrese numero de ficha", id:"inputNewArea" ,required:"true"%>
</div>
<%= f.submit "Guardar", class:"botonNewArea", id:"botonNewArea" %> 
<% end %>

app/views/programas/cursos/edit.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", programa_cursos_url(@programa,@curso), method: :get, class: "IndexArea"%>
    </div>
  </aside>
  <article>
    <legend id="titleNewArea">Editar Ficha</legend>
    <%= render "form" %>
  </article>
</section>
<%= render 'layouts/footer' %>

app/views/programas/cursos/index.html.erb
<%= render 'layouts/navbar' %>

<h2 id="titleProgramasArea">Fichas Programa <%= @programa.nombre %></h2>
<section class="menuArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar",area_programas_url(@programa.area), method: :get, class: "IndexArea"%>
    </div>
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-plus-circle" aria-hidden="true" id="Icono"></i>
      <%= link_to "Registrar ficha", new_programa_curso_url, method: :get,
      class: "IndexArea"%>
    </div>
  </aside>

  <article class="Areas">
    <table class="table">
      <thead id="encabezado">
        <tr>
          <th id="nombreAreas">Fichas</th>
          <th id="nombreAreas">Acciones</th>
        </tr>
      </thead>
      <%= render @cursos %>
    </table>
  </article>
</section>
<%= render 'layouts/footer' %>

app/views/programas/cursos/new.html.erb
<%= render 'layouts/navbar' %>

<section id="newArea">
  <aside class="OpcionesArea">
    <div class="LinkAreas" id="LinkAreas">
      <i class="fa fa-chevron-circle-left" aria-hidden="true" id="Icono"></i>
      <%= link_to "Regresar", programa_cursos_url(@programa,@curso), method: :get, class:
      "IndexArea"%>
    </div>
  </aside>
 <article>
  <legend id="titleNewArea">Registrar Ficha</legend>
  <%= render "form" %>
 </article>
</section>
<%= render 'layouts/footer' %>

app/views/programas/cursos/show.html.erb
<h1>Programas::Cursos#show</h1>
<p>Find me in app/views/programas/cursos/show.html.erb</p>

app/views/programas/index.html.erb
<h1>Programas#index</h1>
<p>Find me in app/views/programas/index.html.erb</p>